/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plantas_vs_zombis;

import javax.swing.ImageIcon;

/**
 *
 * @author HUGO
 */
public class Panel extends javax.swing.JPanel {

    /**
     * Creates new form Panel
     */
    String nombre;
    String ptatque;
    String ptdef;
    String tipo;
    String p;
    String foto;
    public Panel() {
        initComponents();
    }
    public Panel(String a ,int b,int c,String d,String ima,String foto) {
        initComponents();
        this.nombre=a;
        this.ptatque= Integer.toString(b);
        this.ptdef=Integer.toString(c);
        this.tipo=d;
        this.p=ima;
        this.foto=foto;
        
        ingreso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        pataque = new javax.swing.JLabel();
        pdefensa = new javax.swing.JLabel();
        ataque = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        img = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 0, 0));
        Nombre.setText("Nombre");
        add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        pataque.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        pataque.setForeground(new java.awt.Color(255, 0, 0));
        pataque.setText("Nombre");
        add(pataque, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        pdefensa.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        pdefensa.setForeground(new java.awt.Color(255, 0, 0));
        pdefensa.setText("Nombre");
        add(pdefensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        ataque.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        ataque.setForeground(new java.awt.Color(255, 0, 0));
        ataque.setText("Nombre");
        add(ataque, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 51)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
public void ingreso(){
    
    Nombre.setText(nombre);
    pataque.setText(ptatque);
    pdefensa.setText(ptdef);
    ataque.setText(tipo);
    String a =nombre+".jpg";
    
     ImageIcon per = new ImageIcon(foto);
   
          img.setIcon(per);
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel ataque;
    private javax.swing.JLabel img;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pataque;
    private javax.swing.JLabel pdefensa;
    // End of variables declaration//GEN-END:variables
}
